<!DOCTYPE html>
<html lang="en" data-accent-color="indigo" data-content_root="../../">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"><title>The 2021 Python Language Summit: PEP 654 — Exception Groups and except* - Python Blog</title><link rel="shortcut icon" href="../../_static/badge.svg"/><link rel="index" title="Index" href="../../genindex.html" /><link rel="search" title="Search" href="../../search.html" /><script>
    function setColorMode(t){let e=document.documentElement;e.setAttribute("data-color-mode",t);let a=window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches,s=t;"auto"===t&&(s=a?"dark":"light"),"light"===s?(e.classList.remove("dark"),e.classList.add("light")):(e.classList.remove("light"),e.classList.add("dark"))}
    setColorMode(localStorage._theme||"auto");
  </script><link rel="stylesheet" type="text/css" href="../../_static/pygments.css?v=397bb51e" />
    <link rel="stylesheet" type="text/css" href="../../_static/shibuya.css?v=301e5329" />
    <link rel="stylesheet" type="text/css" href="../../_static/copybutton.css?v=76b2166b" />
    <link rel="stylesheet" type="text/css" href="../../_static/sphinx-design.min.css?v=87e54e7c" />
    <link media="print" rel="stylesheet" type="text/css" href="../../_static/print.css?v=20ff2c19" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
:root {
  --sy-f-text: "Inter", var(--sy-f-sys), var(--sy-f-cjk), sans-serif;
  --sy-f-heading: "Inter", var(--sy-f-sys), var(--sy-f-cjk), sans-serif;
}
</style>
    



</head>
<body><div class="sy-head">
  <div class="sy-head-blur"></div>
  <div class="sy-head-inner sy-container mx-auto">
    <a class="sy-head-brand" href="/">
      <img class="light-logo" src="../../_static/badge.svg" alt="Python Blog" height="28" loading="lazy" />
      <img class="dark-logo" src="../../_static/badge.svg" alt="Python Blog" height="28" loading="lazy" />
      <strong>Python Blog</strong>
    </a>
    <div class="sy-head-nav" id="HeadNav">
      <nav class="sy-head-links"><ul><li class="link"><a href="../../index.html">Home</a></li>
      <li class="link"><button type="button">
            <span>Community</span>
            <i class="i-lucide chevron-down"></i>
          </button>
        <ul><li><a href="https://www.python.org/dev/">
                <span>Contributing</span>
                <small>Learn how to contribute to the Python project</small>
              </a></li><li><a href="https://policies.python.org/python.org/code-of-conduct/">
                <span>Code of Conduct</span>
                <small>Review the etiquette for interacting with the Python community</small>
              </a></li><li><a href="https://www.python.org/dev/security/">
                <span>Security</span>
                <small>Overview of PSFs's security protocols</small>
              </a></li></ul>
      </li>
      <li class="link"><button type="button">
            <span>About</span>
            <i class="i-lucide chevron-down"></i>
          </button>
        <ul><li><a href="https://www.python.org/psf-landing/">
                <span>Python Software Foundation</span>
                <small>Details about the PSF</small>
              </a></li><li><a href="https://www.python.org/downloads/">
                <span>Releases</span>
                <small>Explore the latest Python releases</small>
              </a></li></ul>
      </li>
      <li class="link"><button type="button">
            <span>Help</span>
            <i class="i-lucide chevron-down"></i>
          </button>
        <ul><li><a href="https://discord.gg/python">
                <span>Discord Help Forum</span>
                <small>Dedicated Discord help forum</small>
              </a></li><li><a href="https://discuss.python.org/">
                <span>Board Discussions</span>
                <small>Board Discussions</small>
              </a></li></ul>
      </li><li class="link">
          <a href="https://github.com/sponsors/python">
            <span>Sponsor</span></a>
        </li></ul></nav>
      <div class="sy-head-extra flex items-center print:hidden"><form class="searchbox flex items-center" action="../../search.html" method="get">
  <input type="text" name="q" placeholder="Search" />
  <kbd>/</kbd>
</form><div class="sy-head-socials"></div></div>
    </div>
    <div class="sy-head-actions flex items-center shrink-0 print:hidden"><button class="js-theme theme-switch flex items-center"
data-aria-auto="Switch to light color mode"
data-aria-light="Switch to dark color mode"
data-aria-dark="Switch to auto color mode">
<i class="i-lucide theme-icon"></i>
</button><button class="md:hidden flex items-center js-menu" aria-label="Menu" type="button" aria-controls="HeadNav" aria-expanded="false">
        <div class="hamburger">
          <span class="hamburger_1"></span>
          <span class="hamburger_2 -translate-x-2"></span>
          <span class="hamburger_3 -translate-x-1"></span>
        </div>
      </button>
    </div>
  </div>
</div><div class="sy-container mx-auto body">
    <main class="sy-content mx-auto pt-12 px-6 xl:px-12 break-words">
      <article class="yue" role="main">
        
<section id="the-2021-python-language-summit-pep-654-exception-groups-and-except">
<h1>The 2021 Python Language Summit: PEP 654 — Exception Groups and except*<a class="headerlink" href="#the-2021-python-language-summit-pep-654-exception-groups-and-except" title="Link to this heading">¶</a></h1>
<p><em>This was originally posted on blogger</em> <a class="reference external" href="https://pyfound.blogspot.com/2021/05/the-2021-python-language-summit-pep-654.html">here</a>.</p>
<p><a class="reference external" href="https://www.python.org/dev/peps/pep-0654/">PEP 654</a> was authored by Irit
Katriel, Yury Selivanov, and Guido van Rossum. This PEP is currently at the
draft stage. At the <a class="reference external" href="https://pyfound.blogspot.com/2021/05/the-2021-python-language-summit.html">2021 Python Language
Summit</a>, the authors shared what it is, why we need it, and which ideas
they rejected.</p>
<p><a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhe-_2H9U8orSlDfkOZUfyJt9-KAVscD7j3BTPUjP0UL3EPxi-ZDQTJ3w8K0mrDvSzrbz6dYYc3zClMCtoYGG8cd0odseIxLltg6WNND-8LPZCRKuMIcCRzp10wpOwM1RVAQpg/w443-h146/talk-2-authors.png">![Irit Katriel, Yury Selivanov, and Guido van
Rossum</a>](<a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhe-_2H9U8orSlDfkOZUfyJt9-KAVscD7j3BTPUjP0UL3EPxi">https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhe-_2H9U8orSlDfkOZUfyJt9-KAVscD7j3BTPUjP0UL3EPxi</a>-
ZDQTJ3w8K0mrDvSzrbz6dYYc3zClMCtoYGG8cd0odseIxLltg6WNND-8LPZCRKuMIcCRzp10wpOwM1RVAQpg/s1390/talk-2-authors.png)</p>
<blockquote>
<div><p>What Is PEP 654?</p>
</div></blockquote>
<p>The purpose of this PEP is to help Python users handle unrelated exceptions.
Right now, if you’re dealing with several unrelated exceptions, you can:</p>
<blockquote>
<div><ul class="simple">
<li><p><em>Raise one exception</em> and throw away the others, in which case you’re losing exceptions</p></li>
<li><p><em>Return a list of exceptions</em> instead of raising them, in which case they become error codes rather than exceptions, so you can’t handle them with exception-handling mechanisms</p></li>
<li><p><em>Wrap the list of exceptions in a wrapper exception</em> and use it as a list of error codes, which still can’t be handled with exception-handling mechanisms</p></li>
</ul>
</div></blockquote>
<p>PEP 654 proposes:</p>
<blockquote>
<div><ul class="simple">
<li><p>A <a class="reference external" href="https://www.python.org/dev/peps/pep-0654/#exceptiongroup-and-baseexceptiongroup">built-in exception type</a> that wraps other exceptions</p></li>
<li><p>New syntax with <a class="reference external" href="https://www.python.org/dev/peps/pep-0654/#except">except*</a> to handle exception groups</p></li>
</ul>
</div></blockquote>
<p>Each except* clause will be executed once, at most. Each leaf exception will
be handled by one except* clause, at most.</p>
<p>In the discussions about the PEP that have happened so far, there were no
major objections to these ideas, but there are still disagreements about how
to represent an exception group. Exception groups can be nested, and each
exception has its own metadata:</p>
<p><a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEibghDYoNeptJJ3h8Sp9KG7fZgaNKYuVeagkbkIKfZKjU5yR4saI1w1Fe37qpZJTgqDcHlh4fMvRuav2fCA1p0v-ZUNy-qiBvNibDXU3G3wZ237OowXFSl8D_zoMIBYQPF3FWo/s16000/nested-exceptions-500.png">![A nested ExceptionGroup, with
metadata</a>](<a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEibghDYoNeptJJ3h8Sp9KG7fZgaNKYuVeagkbkIKfZKjU5yR4saI1w1Fe37qpZJTgqDcHlh4fMvRuav2fCA1p0v-ZUNy">https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEibghDYoNeptJJ3h8Sp9KG7fZgaNKYuVeagkbkIKfZKjU5yR4saI1w1Fe37qpZJTgqDcHlh4fMvRuav2fCA1p0v-ZUNy</a>-
qiBvNibDXU3G3wZ237OowXFSl8D_zoMIBYQPF3FWo/s500/nested-exceptions-500.png)</p>
<p>Originally, the authors thought that they could make exception groups
iterable, but that wasn’t the best option because metadata has to be
preserved. Their solution was to use a .split() operation to take a condition
on a leaf and copy the metadata:</p>
<p><a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5Uh9SF2iKDnhMIh15b7qGFoUm_RxKYx23RrobVrU6aUa_RJQ-7yw8POAW-Ca88aHaqx-0E3vRMgMqYWyO4IZK2ZgUZWS1PXSZ_qei_FCAuxF2Ej5FqAgFio-6iW9MetauuMo/s16000/split-500.png">![Splitting exception groups with
.split()</a>](<a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5Uh9SF2iKDnhMIh15b7qGFoUm_RxKYx23RrobVrU6aUa_RJQ-7yw8POAW">https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5Uh9SF2iKDnhMIh15b7qGFoUm_RxKYx23RrobVrU6aUa_RJQ-7yw8POAW</a>-
Ca88aHaqx-0E3vRMgMqYWyO4IZK2ZgUZWS1PXSZ_qei_FCAuxF2Ej5FqAgFio-6iW9MetauuMo/s500/split-500.png)</p>
<section id="why-do-we-need-exception-groups-and-except">
<h2>Why Do We Need Exception Groups and except*?<a class="headerlink" href="#why-do-we-need-exception-groups-and-except" title="Link to this heading">¶</a></h2>
<p>There are some differences between operational errors and control flow errors
that you need to take into account when you’re dealing with exceptions:</p>
<p><a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTFI4WBJaj-E8knN3T5oFmt1FWIa2qQtqWM5hdc63iamNZ4R0BQsGFTNP7kACUpesOSPXZjdJ1hNt6iAK_W4uDNoCo9C-SxO6vpPf6UXmdE8V_Yo7iTo-g6bTJCZJqX6kG_Gw/s16000/operational-vs-control-flow-errors.png">![Operational errors vs control flow errors in
Python</a>](<a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTFI4WBJaj-E8knN3T5oFmt1FWIa2qQtqWM5hdc63iamNZ4R0BQsGFTNP7kACUpesOSPXZjdJ1hNt6iAK_W4uDNoCo9C-SxO6vpPf6UXmdE8V_Yo7iTo-g6bTJCZJqX6kG_Gw/s500/operational">https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTFI4WBJaj-E8knN3T5oFmt1FWIa2qQtqWM5hdc63iamNZ4R0BQsGFTNP7kACUpesOSPXZjdJ1hNt6iAK_W4uDNoCo9C-SxO6vpPf6UXmdE8V_Yo7iTo-g6bTJCZJqX6kG_Gw/s500/operational</a>-
vs-control-flow-errors.png)</p>
<p>In _Example <a href="#id1"><span class="problematic" id="id2">1_</span></a> , there is a clearly defined operation with a straightforward
error. But in _Example <a href="#id3"><span class="problematic" id="id4">2_</span></a> , there are concurrent tasks that could contain any
number of lines of code, so you don’t know what caused the KeyError. In this
case, handling one KeyError could potentially be useful for logging, but it
isn’t helpful otherwise. But there are other exceptions that it could make
more sense to handle:</p>
<p><a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj8w-KAlaGie8YtFlLv4X_UsH0VxZlOQPaxGNiFaQDWXITQRpgWkfQ91TO-wZ-pQ-NazFBwl1u9LuG38ELEjoAd8LrdbGtwOYHshgIWZaVD2_1mENqUpaIQbfg_LNXZB1C366s/s16000/CancelledError.png">![asyncio.CancelledError</a>](<a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj8w-KAlaGie8YtFlLv4X_UsH0VxZlOQPaxGNiFaQDWXITQRpgWkfQ91TO">https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj8w-KAlaGie8YtFlLv4X_UsH0VxZlOQPaxGNiFaQDWXITQRpgWkfQ91TO</a>-
wZ-pQ-
NazFBwl1u9LuG38ELEjoAd8LrdbGtwOYHshgIWZaVD2_1mENqUpaIQbfg_LNXZB1C366s/s500/CancelledError.png)</p>
<p>It’s important to understand the differences between operational errors and
control flow errors, as they relate to try-except statements:</p>
<blockquote>
<div><ul class="simple">
<li><p><em>Operational errors</em> are typically handled right where they happen and work well with try-except statements.</p></li>
<li><p><em>Control flow errors</em> are essentially signals, and the current semantics of the try-except statement doesn’t handle them adequately.</p></li>
</ul>
</div></blockquote>
<p>Before <a class="reference external" href="https://docs.python.org/3/library/asyncio.html">asyncio</a>, it wasn’t as
big of a problem that there weren’t advanced mechanisms to react to these
kinds of control flow errors, but now it’s more important that we have a
better way to deal with these sorts of issues. asyncio.gather() is an unusual
API because it has two entirely different operation modes controlled by one
keyword argument, return_exceptions:</p>
<p><a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTSd_jcdpyJocIN8h7zZzCekM73qD_6PkD21eKNSelK11Os5q-y-k2NcKFSDm3RosinMkl5QX5vnjPV_tgf5d3td_uXMGGd2OkRF6-nEFbJe2xRICAcXlbOzhYJq0ybZtDtvI/s16000/asyncio.gather%2528%2529.png">![asyncio.gather()</a>](<a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTSd_jcdpyJocIN8h7zZzCekM73qD_6PkD21eKNSelK11Os5q-y-k2NcKFSDm3RosinMkl5QX5vnjPV_tgf5d3td_uXMGGd2OkRF6-nEFbJe2xRICAcXlbOzhYJq0ybZtDtvI/s500/asyncio.gather%2528%2529.png">https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTSd_jcdpyJocIN8h7zZzCekM73qD_6PkD21eKNSelK11Os5q-y-k2NcKFSDm3RosinMkl5QX5vnjPV_tgf5d3td_uXMGGd2OkRF6-nEFbJe2xRICAcXlbOzhYJq0ybZtDtvI/s500/asyncio.gather%2528%2529.png</a>)</p>
<p>The problem with this API is that, if an error happens, you still wait for all
of the tasks to complete. In addition, you can’t use try-except to handle the
exceptions but instead have to unpack the results of those tasks and manually
check them, which can be cumbersome.</p>
<p>The solution to this problem was to implement another way of controlling
concurrent tasks:</p>
<p><a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhm0DIoT7s4hMtOIpl8Gi7Zn5GzNz8IHHZFjKJoucKu386IX7lz41gLBo9YbeKpbUH5T2z3qJzizj4FRxZh9lQ2a9ByU_9J1f8mePVQIUr1tN5aixhjCoLklW2t7oe6PgST5bU/s16000/asyncio.TaskGroup.png">![asyncio.TaskGroup</a>](<a class="reference external" href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhm0DIoT7s4hMtOIpl8Gi7Zn5GzNz8IHHZFjKJoucKu386IX7lz41gLBo9YbeKpbUH5T2z3qJzizj4FRxZh9lQ2a9ByU_9J1f8mePVQIUr1tN5aixhjCoLklW2t7oe6PgST5bU/s500/asyncio.TaskGroup.png">https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhm0DIoT7s4hMtOIpl8Gi7Zn5GzNz8IHHZFjKJoucKu386IX7lz41gLBo9YbeKpbUH5T2z3qJzizj4FRxZh9lQ2a9ByU_9J1f8mePVQIUr1tN5aixhjCoLklW2t7oe6PgST5bU/s500/asyncio.TaskGroup.png</a>)</p>
<p>If one tasks fails, then all other tasks will be cancelled. Users of asyncio
have been requesting this kind of solution, but it needed a new way of dealing
with exceptions and was part of the inspiration behind PEP 654.</p>
</section>
<section id="which-ideas-were-rejected">
<h2>Which Ideas Were Rejected?<a class="headerlink" href="#which-ideas-were-rejected" title="Link to this heading">¶</a></h2>
<p>Whether or not exception groups should be iterable is still an open question.
For that to work, tracebacks would need to be concatenated, with shared parts
copied, which isn’t very efficient. But iteration isn’t usually the right
approach for working with exception groups anyway. A potential compromise
could be to have an iteration utility in traceback.py.</p>
<p>The authors considered teaching except to handle exception groups instead of
adding except*, but there would be too many backwards compatibility problems.
They also thought about using an except* clause on one exception at a time.
Backwards compatibility issues wouldn’t apply there, but this would
essentially be iteration, which wouldn’t help.</p>
</section>
</section>

<div class="section ablog__blog_comments">
  
  


<div class="section ablog__prev-next">
  <span class="ablog__prev">
    
    
    Previous:
    
    <a href="2021-05-the-2021-python-language-summit-welcome.html">
      
      <span>The 2021 Python Language Summit: Welcome, Introductions, Guidelines</span>
    </a>
    
  </span>
  <span class="ablog__spacer">&nbsp;</span>
  <span class="ablog__next">
    
    
    Next:
    
    <a href="2021-05-the-2021-python-language-summit_16.html">
      <span>The 2021 Python Language Summit: Progress on Running Multiple Python Interpreters in Parallel in the Same Process</span>
      
    </a>
    
  </span>
</div>

  
  
</div>

      </article>
      
    </main>
  </div><footer class="sy-foot">
  <div class="sy-foot-inner sy-container mx-auto">
    <div class="sy-foot-reserved md:flex justify-between items-center">
      <div class="sy-foot-copyright"><p>2024, Python Software Foundation</p>
  
  <p>
    Made with
    
    <a href="https://www.sphinx-doc.org/">Sphinx</a> and
    
    <a href="https://shibuya.lepture.com">Shibuya theme</a>.
  </p>
</div>
      <div class="sy-foot-socials"></div>
    </div>
  </div>
</footer>
      <script src="../../_static/documentation_options.js?v=8a448e45"></script>
      <script src="../../_static/doctools.js?v=9a2dae69"></script>
      <script src="../../_static/sphinx_highlight.js?v=dc90522c"></script>
      <script src="../../_static/clipboard.min.js?v=a7894cd8"></script>
      <script src="../../_static/copybutton.js?v=f281be69"></script>
      <script src="../../_static/design-tabs.js?v=f930bc37"></script>
      <script src="../../_static/shibuya.js?v=3cc430e2"></script></body>
</html>